import Massagem from '../../../assets/images/massagem.jpg';

const services = [
  {
    category: 'Cílios',
    img: Massagem,
    items: [
      { text: 'Cílios Completo', price: '180,00' },
      { text: 'Manutenção 50%', price: '99,00' },
      { text: 'Manutenção 70%', price: '69,00' },
      { text: 'Lash Lifting', price: '159,00' },
    ],
  },
  {
    category: 'Pigmentações',
    img: Massagem,
    items: [
      { text: 'Tinturinha Temporária', price: '29,00' },
      { text: 'Brow Lumination', price: '149,00' },
      { text: 'Micro NanoBlanding', price: '380,00' },
      { text: 'Micro Labial', price: '499,00' },
      { text: 'Retoque Micro', price: '40,00' },
    ],
  },
  {
    category: 'Estética Facial',
    img: Massagem,
    items: [
      { text: 'Limpeza de Pele', price: '129,00' },
      { text: 'Peeling Químico', price: '99,00' },
      { text: 'Revitalização Facial', price: '79,00' },
      { text: 'Nutrição Facial', price: '79,00' },
      { text: 'Hidra Lips Gloss (Sessão)', price: '249,00' },
      { text: 'Drenagem Linfática Facial', price: '69,00' },
      { text: 'Massagem Relaxante Facial', price: '99,00' },
    ],
  },
  {
    category: 'Estética Corporal',
    img: Massagem,
    items: [
      { text: 'Massagem Relaxante', price: '99,00' },
      { text: 'Drenagem Linfática', price: '89,00' },
      { text: 'Liberação Miofascial', price: '119,00' },
      { text: 'Massagem Desportiva', price: '119,00' },
      { text: 'Gomage e Banho de Lua', price: '99,00' },
    ],
  },
  {
    category: 'Serviços',
    img: Massagem,
    items: [
      { text: 'Sobrancelhas', price: '40,00' },
      { text: 'Tinturinha', price: '29,00' },
      { text: 'Micro Nanoblaiding', price: '380,00' },
    ],
  },
  {
    category: 'Depilação Cera',
    img: Massagem,
    items: [
      { text: 'Buço', price: '21,00' },
      { text: 'Queixo/Pescoço', price: '21,00' },
      { text: 'Nariz', price: '18,00' },
      { text: 'Laterais do Rosto', price: '39,00' },
      { text: 'Rosto Completo', price: '69,00' },
      { text: 'Axilas', price: '31,00' },
      { text: 'Braços', price: '39,00' },
      { text: 'Íntima Completa', price: '59,00' },
      { text: 'Íntima Simples', price: '46,00' },
      { text: 'Perianal', price: '21,00' },
      { text: 'Nádegas', price: '31,00' },
      { text: 'Coxa', price: '38,00' },
      { text: 'Meia Perna', price: '38,00' },
      { text: 'Perna', price: '69,00' },
      { text: 'Lombar', price: '28,00' },
      { text: 'Costas', price: '62,00' },
      { text: 'Abdômen', price: '39,00' },
    ],
  },
  {
    category: 'Depilação Lazer (F)',
    img: Massagem,
    items: [
      { text: 'Buço', price: '52,00' },
      { text: 'Queixo/Pescoço', price: '52,00' },
      { text: 'Lateral do Rosto', price: '52,00' },
      { text: 'Rosto Completo', price: '120,00' },
      { text: 'Axilas', price: '79,00' },
      { text: 'Linha Alba', price: '35,00' },
      { text: 'Braços', price: '139,00' },
      { text: 'Íntima Completa', price: '189,00' },
      { text: 'Íntima Simples', price: '105,00' },
      { text: 'Coxas', price: '129,00' },
      { text: 'Meia Perna', price: '129,00' },
      { text: 'Perna', price: '259,00' },
      { text: 'Costas', price: '189,00' },
    ],
  },
  {
    category: 'Depilação Lazer (M)',
    img: Massagem,
    items: [
      { text: 'Barba Completa', price: '179,00' },
      { text: 'Pescoço e Maçãs', price: '79,00' },
      { text: 'Axilas', price: '89,00' },
      { text: 'Braços', price: '159,00' },
      { text: 'Costas', price: '239,00' },
      { text: 'Abdômen e Tórax', price: '269,00' },
      { text: 'Pernas', price: '289,00' },
    ],
  },
];

export default services;
